import { createContext, Fragment, useContext, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import type { CareFeedback, CareFeedbackKind, CareState } from '../../../shared/api/care';
import { cx } from '../ui/controls';
import { Icon } from '../ui/Icon';
import { commentRangesFor, splitRuns, type CareView } from './careModel';
import type { SegmentSelection } from './useSegmentSelection';

export interface ReadingContextValue {
  view: CareView;
  snapshotId: number;
  comments: CareState['comments'];
  activeCommentId: number | null;
  onOpenComment: (commentId: number) => void;
  /** Switches to the tab holding a passage, then scrolls to it. */
  reveal: (segmentId: string) => void;
  /** This clinician's feedback on the snapshot being read, by target key. */
  feedback: ReadonlyMap<string, CareFeedback>;
  canFeedback: boolean;
  /** `kind: null` clears the clinician's verdict on that item. */
  onFeedback: (target: { segmentId?: string; sectionKey?: string }, kind: CareFeedbackKind | null) => void;
}

const ReadingContext = createContext<ReadingContextValue | null>(null);
export const ReadingProvider = ReadingContext.Provider;

function useReading(): ReadingContextValue {
  const context = useContext(ReadingContext);
  if (!context) throw new Error('Passage must be inside ReadingProvider');
  return context;
}

type Voice = 'patient' | 'generated' | 'record' | 'clinic' | 'plain';
const VOICE_CLASS: Record<Voice, string> = {
  patient: 'font-display text-[19px] leading-[1.35] text-ink',
  generated: 'text-[15px] leading-relaxed text-[#1E2643]',
  record: 'text-[15px] text-ink-2',
  clinic: 'text-[15px] text-ink',
  /** No type styling; the caller sets size and colour. */
  plain: '',
};

/**
 * The only place assessment text is rendered. A stored passage gets a
 * `data-segment-id`, which is what makes it selectable for comments, and its
 * existing comments are drawn as highlights. Headings never pass through here.
 */
export function Passage({ id, fallback, as = 'p', voice, className }: { id: string; fallback?: string | null; as?: 'p' | 'span' | 'div'; voice?: Voice; className?: string }) {
  const { view, snapshotId, comments, activeCommentId, onOpenComment } = useReading();
  const segment = view.segments.get(id);
  const text = segment?.text ?? fallback ?? '';
  if (!text) return null;
  const Tag = as;
  const tone = VOICE_CLASS[voice ?? (segment?.voice as Voice | undefined) ?? 'generated'];
  if (!segment) return <Tag className={cx(tone, className)}>{text}</Tag>;
  const { ranges } = commentRangesFor(id, snapshotId, text.length, comments);
  return (
    <Tag data-segment-id={id} className={cx(tone, 'scroll-mt-28 whitespace-pre-wrap rounded-[3px] transition-[background-color,box-shadow] duration-500', className)}>
      {splitRuns(text, ranges).map((run) => run.commentIds.length ? (
        <mark
          key={run.start}
          onClick={() => onOpenComment(run.commentIds[0])}
          className={cx(
            'cursor-pointer rounded-[2px] text-inherit',
            run.resolvedOnly ? 'bg-transparent underline decoration-ink-3/50 decoration-dotted underline-offset-4' : 'bg-[#FFEDB8]',
            run.commentIds.includes(activeCommentId ?? -1) && 'bg-[#FFDF85] shadow-[0_0_0_2px_#FFDF85]',
          )}
        >
          {run.text}
        </mark>
      ) : <Fragment key={run.start}>{run.text}</Fragment>)}
    </Tag>
  );
}

const REF_WORDS: Array<[string, string]> = [
  ['answer:', 'See answer'],
  ['visit:complaint', 'See reason for visit'],
  ['visit:note', 'See their note'],
  ['visit:', 'See visit record'],
  ['emergency:', 'See warning'],
];

/** "See answer" link that takes the reader to the passages behind an item. */
export function RefLink({ refs, label }: { refs: string[]; label?: string }) {
  const { view, reveal } = useReading();
  const target = refs.find((ref) => view.segments.has(ref));
  if (!target) return null;
  const words = label ?? REF_WORDS.find(([prefix]) => target.startsWith(prefix))?.[1] ?? 'See where';
  return (
    <button type="button" onClick={() => reveal(target)} className="inline-flex shrink-0 items-center gap-1 rounded-md px-1 text-[13px] font-semibold text-brand-700 hover:bg-brand-select focus-visible:outline-2 focus-visible:outline-brand">
      {words}
    </button>
  );
}

/** One plain label and a dashed rule mark everything Priage generated. */
export function GeneratedBlock({ children, label = 'Generated by Priage from the answers. Check it against them.', className }: { children: ReactNode; label?: string | null; className?: string }) {
  return (
    <div className={cx('flex flex-col gap-3 border-l-2 border-dashed border-brand-rule pl-4', className)}>
      {label && <p className="text-[13px] font-semibold text-brand-700">{label}</p>}
      {children}
    </div>
  );
}

export function SectionTitle({ children, aside, action }: { children: ReactNode; aside?: ReactNode; action?: ReactNode }) {
  return (
    <div className="flex items-baseline gap-3">
      <h3 className="text-[15px] font-semibold text-ink">{children}</h3>
      {aside && <span className="text-[13px] text-ink-3">{aside}</span>}
      {action && <span className="ml-auto">{action}</span>}
    </div>
  );
}

const REVEAL_ON_HOVER = 'opacity-0 focus-within:opacity-100 focus-visible:opacity-100 [@media(hover:none)]:opacity-100';

/**
 * Quiet Useful / Not right buttons on one generated item. They appear when the
 * row is hovered or focused, floating over its right edge so they take no room,
 * and sit inline after the text once the clinician has used them. Rows that
 * hold one set `relative` and `--row-bg` (the colour the buttons sit on).
 */
export function FeedbackControl({ segmentId, overlay = true }: { segmentId: string; overlay?: boolean }) {
  const { view, feedback, canFeedback, onFeedback } = useReading();
  if (!canFeedback || view.schemaVersion !== 2 || view.segments.get(segmentId)?.voice !== 'generated') return null;
  const mine = feedback.get(segmentId);
  const choice = (kind: CareFeedbackKind, label: string) => {
    const on = mine?.kind === kind;
    return (
      <button
        type="button"
        aria-pressed={on}
        title={on && mine.note ? mine.note : undefined}
        onClick={() => onFeedback({ segmentId }, on ? null : kind)}
        className={cx('inline-flex h-6 items-center gap-1 rounded-md px-1.5 font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-brand', on ? 'text-ink' : 'text-ink-3 hover:bg-ink/5 hover:text-ink')}
      >
        {on && <Icon name="check" size={12} />}{label}
      </button>
    );
  };
  return (
    <span
      role="group"
      aria-label="Your feedback on this item"
      className={cx(
        'inline-flex shrink-0 items-center text-[12px] transition-opacity',
        mine ? 'opacity-100' : cx(REVEAL_ON_HOVER, 'group-hover/item:opacity-100'),
        !mine && overlay && 'absolute right-0 top-0 bg-[var(--row-bg,white)] pl-2 shadow-[-14px_0_12px_-6px_var(--row-bg,white)]',
      )}
    >
      {choice('USEFUL', 'Useful')}
      {choice('NOT_RIGHT', 'Not right')}
    </span>
  );
}

/** "Something missing?" for a generated section, shown on hover like the item buttons. */
export function MissingLink({ sectionKey }: { sectionKey: string }) {
  const { view, feedback, canFeedback, onFeedback } = useReading();
  if (!canFeedback || view.schemaVersion !== 2) return null;
  const mine = feedback.get(`missing:${sectionKey}`);
  return (
    <button
      type="button"
      onClick={() => onFeedback({ sectionKey }, 'MISSING')}
      className={cx('rounded-md px-1.5 text-[12px] font-semibold transition-[opacity,color] hover:text-ink focus-visible:outline-2 focus-visible:outline-brand', mine ? 'text-ink-2' : cx('text-ink-3', REVEAL_ON_HOVER, 'group-hover/section:opacity-100'))}
    >
      {mine ? 'You noted something missing' : 'Something missing?'}
    </button>
  );
}

export function SelectionToolbar({ selection, canComment, commentHint, canQuote, onComment, onCopy, onQuote }: {
  selection: SegmentSelection | null; canComment: boolean; commentHint: string; canQuote: boolean;
  onComment: () => void; onCopy: () => void; onQuote: () => void;
}) {
  const toolbar = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(0);
  // Measure, then keep the whole toolbar on screen rather than just its centre.
  useLayoutEffect(() => { setWidth(toolbar.current?.offsetWidth ?? 0); }, [selection, canComment, canQuote]);
  if (!selection) return null;
  const top = Math.max(8, selection.top - 50);
  const half = width / 2;
  const left = Math.min(Math.max(half + 8, selection.left), window.innerWidth - half - 8);
  const keepSelection = (event: React.MouseEvent) => event.preventDefault();
  return (
    <div
      ref={toolbar}
      role="toolbar"
      aria-label="Selected text"
      onMouseDown={keepSelection}
      className="fixed z-[90] flex -translate-x-1/2 items-center gap-0.5 whitespace-nowrap rounded-xl bg-ink p-1 font-clinic text-[13px] font-semibold text-white shadow-[0_14px_28px_-12px_rgba(14,22,48,.6)]"
      style={{ top, left }}
    >
      {!selection.valid ? (
        <span className="px-3 py-2 text-[#DCE3F8]">Select within one passage to comment</span>
      ) : (
        <>
          {canComment && <button type="button" onClick={onComment} className="flex h-[34px] items-center gap-1.5 rounded-lg bg-white/12 px-3 hover:bg-white/20"><Icon name="message" size={15} />Comment</button>}
          <button type="button" onClick={onCopy} className="h-[34px] rounded-lg px-3 text-[#DCE3F8] hover:bg-white/12 hover:text-white">Copy</button>
          {canQuote && <button type="button" onClick={onQuote} className="h-[34px] rounded-lg px-3 text-[#DCE3F8] hover:bg-white/12 hover:text-white">Quote in note</button>}
          {!canComment && <span className="px-2 text-[12px] font-medium text-[#AEB8D6]">{commentHint}</span>}
        </>
      )}
    </div>
  );
}
